apiVersion: v1
kind: Secret
metadata:
    name: porkbun-api-token
    namespace: security
stringData:
    api-key: ENC[AES256_GCM,data:axdkAMU1AYBFKHshDryyildALU7Zu16TyZa6v1rEGvLY3ZkQgNJ28R2WcAL4Sv58t6d5HhHD2IKxeAqgRvnJ78P0dZM=,iv:x0pxyIL4D/3ZEYkddEHlG/+uscvIzYq1EBJN7JyvOAQ=,tag:TpZcBlYrkXKNkc43waNqIA==,type:str]
    secret-key: ENC[AES256_GCM,data:p621n9G3dU3jdqyf4N+xnviM24n/I4X48Ql8jgwzJbY9tr7dmQNlVRvjcQIfYpz1Xzv58M1nlvpWPYm9nxQeY9CHqGU=,iv:kmIknPEU/524vAxWOs5hP64oyJM81r8CB1B5KB1RdG0=,tag:b9vm+g/FcmvM77WHqRQsiQ==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dko0Y0g3Y2FETU9GcTZh
            K0tKYk9kdFZTYzd1NkRYL1VxTnZYOG4wMEZJCnh2Rk5Qelo2M3Y1RWc3a0pqZDZU
            dHhRVGgyWUhjbmp2bEV5RG0rWVJITlEKLS0tIFBIUUc0R0trOUpkUlo4U0hGTkZP
            ZkU1Z3htUFBVYm1ITXdpRDVsanV4NU0KIF4NdF20bSUkkAq2FyttvkpKc7mz7OGb
            rKg8N+7DOULbIUgiJ/kJsGpQTSFYa6Fy0GBck/YQ/LnD95I4WF4AOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T09:08:07Z"
    mac: ENC[AES256_GCM,data:h2N4hhF+tUzXqKrT+goCaNp/yQK5J1kvZId2W5Zq5j6ezC78e6Ep2KoAU3oeNKgh+Pap7Vor22+EXCC3XaVeHkerK0ZpVhlm4TUCWwM1tXNU+TzAYRZdHEOyL7drNtDkhHnIVYgaUZmXSFSUo5C73nE2UTbZqIqrwX5pkSMNpJM=,iv:mwDVRdaXjaphZ8kOlw8NO7FWU1OfAUlizVxroK0GdG4=,tag:spDLmFQMKmTaoWn3wUdDBw==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
