apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:Od7Hl2/9z955dEQ=,iv:snu9HzCw4vEGAyLoSdtZ6nbjojDOPV2yMRmnkeShU0U=,tag:T2Zf9QrHL77tW3AcaA6umg==,type:str]
    EMAIL_ADDRESS: ENC[AES256_GCM,data:PnCbpFWoHUpcc9sszI7F8g1vtM2oQzVPjA==,iv:QW0UJgFXKnijdllf8JsQyCvsWnWoc+xp08Z72QCOHPE=,tag:LQnQoU4U/YQvIUo/3s4wqw==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMzdsd3YvaHA5ZlorejFS
            NUJLUlVGQ2tXS01oTVlhdXdzTVA1Z3htT2cwCmJEM3NydnE1RUh5L3NIbThpaHBK
            RHk0ZE83NS9UNjhSVUY0WUM1TmcrNWsKLS0tIFl3MWdlVEVySkp3b0hHazJUMnFn
            Rnl2YjdLR0ZsMEk5N2hTZ3FVS1B4cFkK5pIkLFB3OnjR+Of76MhFwa/LBgrWCSxN
            uxKix9jdpn+kUBxNOB1wKVbT4sjPpBwXz58y0Qq9KgA9b8m0HE5joQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T09:07:31Z"
    mac: ENC[AES256_GCM,data:XgiQjp0g1RtwIzM9chrQSUE9lsQiiTcNfWkjVIMNRpvop3gSf1MgX86fKJJQaiTrt4g2yNfTcwUiRo0Kn77IYROdqlIiAx+/ZQg2egthRU4G2VH5cLnBCQMGTl5pp53062i+tHwXrUHwMsPEpjOcU0AzJ8Aow9Ku7/tg+qXXC4M=,iv:AFmUf3kaBVGfXL2wbcJDws83o0tOEpeALJRH5ZXucuU=,tag:gfMbH2jkRTmOVN9z0rQ5fQ==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
