apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:Od7Hl2/9z955dEQ=,iv:snu9HzCw4vEGAyLoSdtZ6nbjojDOPV2yMRmnkeShU0U=,tag:T2Zf9QrHL77tW3AcaA6umg==,type:str]
    EMAIL_ADDRESS: ENC[AES256_GCM,data:PnCbpFWoHUpcc9sszI7F8g1vtM2oQzVPjA==,iv:QW0UJgFXKnijdllf8JsQyCvsWnWoc+xp08Z72QCOHPE=,tag:LQnQoU4U/YQvIUo/3s4wqw==,type:str]
    PAGERDUTY_INTEGRATION_KEY: ENC[AES256_GCM,data:3CHbrTN5DFXJ6eLBDTMs51sNSdKBAeAdk2rCYQwNJJ8=,iv:YXGo1Be6+SMGZqxmYPoLwLyIGNjStzqECobIG9gKrzk=,tag:BkWDQ6xG99XAw3Sf6YLYSw==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:3lhVuT1Qc0MqXUE=,iv:INYQOzLRp2LdoU/vMV3znOwHYPszu/AkXqY3qgLya9s=,tag:nEVY8wniD1/fMYrvF5zhqA==,type:str]
    CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:sB1MVUk4ZUqR1KlMNVEeOsIRB/iW3EBdScy1IEGJz0DOqul3TQOy5JGW01TNzzZIV3pcgsQs7ESL50LymVNveTwHpI6CdEvOPE0A8NE+jN1D5aMMwuiC9/FRggHdH13BcJVrc9i2KHW+R0xmiMV++hY9nvnFoEU6Uj1BcPQVLcn8/WqGMEweiC08fhorrgiHVCZnwiz4CGZPFFVWXUayYAELhm0lgX3JHhf8u4NyXKf1nZ5hNSONug==,iv:+elLs508amipXwUow/JfweI7FkZKS6VDMDOvQ/M7jvQ=,tag:tibagNAL+NqhE5HdC8MuqQ==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMzdsd3YvaHA5ZlorejFS
            NUJLUlVGQ2tXS01oTVlhdXdzTVA1Z3htT2cwCmJEM3NydnE1RUh5L3NIbThpaHBK
            RHk0ZE83NS9UNjhSVUY0WUM1TmcrNWsKLS0tIFl3MWdlVEVySkp3b0hHazJUMnFn
            Rnl2YjdLR0ZsMEk5N2hTZ3FVS1B4cFkK5pIkLFB3OnjR+Of76MhFwa/LBgrWCSxN
            uxKix9jdpn+kUBxNOB1wKVbT4sjPpBwXz58y0Qq9KgA9b8m0HE5joQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T16:19:05Z"
    mac: ENC[AES256_GCM,data:3xXt0YMuZYRQkeznRBMR5jj4CXr7UFzT9iKSTDiqTWFLo1e0Q7FN1srvNQnGrfOP9kfoWLgHrBWH8JOMeqqdYRRAZXfF0oGfQcUd5biHoeq/lTnpHqpjqi7jlEa3K1u/aKAFxnxz6leqGQ1opM1RSvBwMgTqptTQRzI3mdTuwhY=,iv:bUj1E5Nrs3x4xo73RSyufz500dKMIdDlWaVbp2DQ5Cg=,tag:Ka+AAHHF2VWd3cmHvxfHYQ==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
