apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:HUYaRUgPGA3CSHo=,iv:kcYLgMlR5pyIqBzNfGDS6iJHnyjBCx8hLidd0AX80yY=,tag:B5NsT5kEMtKbJLW1OlsMiw==,type:str]
    EMAIL_ADDRESS: ENC[AES256_GCM,data:1zh257lh//GK5af8rddl4gqOXCzHts7LpQ==,iv:2/vBxkogTCh0S5/gJtEGeFUJRLl/I1o5Pm/c+weicy4=,tag:qOeeN6iDP1+32Xy/paxzYg==,type:str]
    PAGERDUTY_INTEGRATION_KEY: ENC[AES256_GCM,data:c1WBOaIR8uUR5xqSOljZ9AqEIXjeINFuRYiZIdNaudM=,iv:wptwtDziv0OWVm1QZUZFDFfoWg+wtsN9tS4fq8qQDCI=,tag:mJeS7iKrE1u9E3irksZtPg==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:abezGYZG6QCLQs0=,iv:fq0iNDWSRpUMD93cugvcMXW93s6oeOZ4mVBp38e4AiE=,tag:dWquKgbfCyZyYG2h5EneQQ==,type:str]
    CLUSTER_TIMEZONE: ENC[AES256_GCM,data:1NTzIzeHk6M7jr3MtP062w==,iv:IxYM0XILR+xTpLy5VUq0sxxjbv09PasHKEa6wM9OTpc=,tag:IX2FrXHYRmmqnCu3Yv4tgQ==,type:str]
    REGISTRY_URL: ENC[AES256_GCM,data:MPBz3I7VjFAeybV4cR6PpE5w4Tg=,iv:XMr5cFWRLtL9mnNc7ItiQLrMCCXanQHUwmlFP6U1h7k=,tag:ddjic9epYTMwpXTXXNj4DQ==,type:str]
    APPS_SUBDOMAIN: ENC[AES256_GCM,data:PEQNLvvH3ZeNA5rDAlEcDg==,iv:7nn8BTqU8DKCVzOMZMU0B7tv4SOzixMqE1udA8F+xOw=,tag:hK93FlIv4T+wuGpxln1pcA==,type:str]
    CLOUDFLARE_TUNNEL_TOKEN: ENC[AES256_GCM,data:q3bJYKcaZrQy7RJIw1Gred62yb2I1ZdC32gIERJSY2iU1IBeAstDy/ediaKG4kiSK+pH4kR3MXaGClAztfkugDMvcudjvDiAPUexn0c87fwlaqRkmw7g7fFaXtuJivlubYNMnbuXODetUS7WywqkhexmccSuiHCy3NHyGhJpH/BO2QosPF9LhvtyyiQP86k/+kLDPsRb/Pr2KE2uPRaJlW3fCkqBq+fQVVA2tqNbU06MGLWbjOtlHA==,iv:ZlSR3tnwWYiRKHwbx0RxeqU9zd3dBr8yurcz83TLilA=,tag:lQSr9R2LNg76QeQlIcjHJw==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaVBaQzM3NXB5ZHljRjk4
            VmVkUEI2OG9lSXpsazdqRnRrQlFsVE5LU1h3CmJUVWdoLzRzUXpGSHp1RFZwUElV
            TWw3eTBOVkh3YzRpUkZ6RWorK2pKcVkKLS0tIDR3eFBkeXhVaVhxSlZhUjlHcnJT
            Y0hhTkoyRGpscVdLWHpKdnc4WGliRjAKIcgIjwmI0oWXa2daEmrJTa0yp6Pw9drG
            9ZbQm8W7DHdXE0QCtKxUUFnrs06nShyTgHaxNAjw4DfD3TR19DuHsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T15:09:10Z"
    mac: ENC[AES256_GCM,data:2Y4Vn4vCKICALsrjlNIg6riWo+iGgDSCsgE6xUGy84l/Fw+biOitC+e4hyx+Hierf6KvDWdvkjoatHYvUgahHmGHeHZy6PKlAxNda4QpBLDtynjc9unLbAu7VDX6eQh5X/jRTbtxjnXvUhV/Q8xjfjwoNtldmwJlztJ6Ts1XKMs=,iv:sTKK8mAge7ITBwXZTE0EJQtxIKS4Qg3/VoiPyklFkR0=,tag:DabB8Gy72AkjOxzp/FAi2A==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
