apiVersion: v1
kind: Secret
metadata:
    name: linkding-postgres-credentials
    namespace: home
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:poAx2/8odyU=,iv:kCOhNpvh/ieCQK5VDJnZhQ5QR4hrr7WRzsu8+xHz0V0=,tag:Lf9NTJKY0EWVu6Hr4UZLQw==,type:str]
    password: ENC[AES256_GCM,data:Am51q6JqKQg5e6C1iU5zR1VsIDqgTSEZ,iv:1K9D4/iYPqR0FrNhuIiD3NGuFM5lzvTwZCfwwd2OxwU=,tag:hHi6txFUCrc+7Uimoal0mw==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWGF0UjBPZzllT0V0Wld1
            VjZzSWdhS0ZNalgzSWtLbGlvMmxwT2p2ZzJRCllZQUNSSmpsbjVCaWcxcGpMbk1Y
            Q0lxWG5rWVdvcjQvZmNKWW8rK2t2RkUKLS0tIHRHMjA4RHE5VzA1YnBpY3FMdU1o
            VG4zL3FXMzlGemhwWk4zVVRHaElGNkkK8ScK4XGPZLRqolDrFAiQUrhSNKgCYjCc
            JyB7WohuPuXyQMEW2hSvFFnxEAk5r+Z6zvlMu92am00XKpKMUwPISg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T08:16:07Z"
    mac: ENC[AES256_GCM,data:CkEFudn8et4CThDxZZzisMS0vVCZv6Am/z1EoIf8D9OF9kfNCkHIWuNN0TtTlm0+43vFWeATfWspE5mnjWjlCzJnnZilZoiptodE4AMh+QcwpV0GFUNlY+zmWDGNPKLOdCX0utGzCi4sq1j2Vx/Uw8lPFG1pNq9k0DDGFjTmwmQ=,iv:cCPqthwcllNmGYQ/6LUNBtx5/6veS87nNDLweckO5CE=,tag:TBZ4UlASYPgQiCIN/Ae13g==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
