apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:j5RO4OzoCyt2AZoRFUoOON8teVqojCXGThWhPvuEs3nJgkbLWF4vJQ==,iv:qn7w9ODrDhKDTF28eX+QAxk4pskN7wgdrbOA9HIBYVo=,tag:Qe715HsDjPw7CUNVRM+1LQ==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd0ZrZXlOYkxIeTRjbjQz
            bGM3S0QwZEh6T2VZdXZNOGtDVGFPd01GMEdRClFBMytmVmpxaUQ1TUhJN2xIN1Fj
            cmg2dTJoSEYyR1RobjAzaHIyRnIxSUEKLS0tIDZ6L0d5SW1jQ094SzdyVkhsNlNy
            dkk0VDE2RExrVmxqM1JJZ2hTMHQvK0EKx5JyY+bQCeeMJyMgngunqMg9Fg8ARSBv
            cfcb3kB5HyTT/BJvJJZGBJcPJjlWaU5l/Rh4Yq1De0IS86xjjC+Q2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T13:26:07Z"
    mac: ENC[AES256_GCM,data:jdsPMzn8LF6LqGRKuplWM0XBRqHewsbuGlikKOaoDe85hon3459xzxFxzrRrM8r6+NCWXLzYxzSlew5uBI8hBsiaQ12rKpoNaoo5dhkE+KkNOSRJLRj+E7hydBu1wrLR7z6zRWxc8WtUggwST3H93jiN1tim7GNFWOXnb3dTniI=,iv:7LisNoYWydKBSUEBgdd6p0KSccMI/P9D5sxv/pSjMYE=,tag:9/dV01fODZh2wKctAH9U1A==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
