---
apiVersion: v1
kind: Service
metadata:
  name: cloudflare-tunnel-flux-webhook
  namespace: flux-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: flux-webhook.k8s-lab.dev
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: 4e55e2cf-b57a-44aa-8c19-e201cecbe23c.cfargotunnel.com
