apiVersion: v1
kind: Secret
metadata:
    name: n8n-git-ssh
    namespace: automation
type: Opaque
stringData:
    id_ed25519: ENC[AES256_GCM,data:77qQ2IM3HZHUe8n8ctNGDL1cnTt23wnZXHK+j+d7VRJljj47MaA3f2/a85cDJzLYzydlmBYdra882CKFCWeb7Xf16nvfh5j7+t5VANTDN9w7WZnNwj+6L+iyWaq70iYEaTPXTatQBl634zVClfUoj3T3k5WEgb9Im3kvAI31RyxJuYO/CqooCRAXOxkagOtNB9ZLCGZ33BVAL6bkVa+jrIgxqJ5xFYKb98EwU+QEu8frGgY1L11iD+nkb0iB9AGa4tEs67kQEsN5NLO2MpTYiI2s0Pd2J+PvvjiHpc4ZhQG+5dLRtFti0Xhts0p0Riq+gPImuKlKRHElBunw3SEK3mO0IaD+trwwXLSWIKoQeF/UUQ6Uft0SnaDn+HMUZ9qk4V58Ho18ycc0HbbCqEh2k+UhMrvMagRkvxkyK8gqqnu2pYgvCJK/EQvf3MZx8MS7UWEhsYcALWLq89837cn/2OOdishqYGcdbUo6wHx0T1Q7CgOXkgzJysrncFcFue/dm+oglN9JgG4a2jHQ2DfIqAqW1szaXZwt3NUz,iv:KjaRCsBLowE2p6aAVS6m4p2HjZ263Gjvsh2i5PPolfE=,tag:HOCqpqqPnP/bXVjZLqT05w==,type:str]
    known_hosts: ENC[AES256_GCM,data:G0S0BJC+Kd3VkE2+nu4erjf86DW38JxKyuzF8qI3H9JOpB+jVsaGtJiIo2vcinaxCKpsRh+IZ2jdCHszcavyyLQ5kW1n8ryv4l+J/mxpuuUqE8hmT9KRZzLKSG45wK7bz2rqG7o2ZPWdcl8uuGRG8vzcZl2HIOU1xsHIKNH0s0EG4IJt26vOoy8ntFLMny3EYQN3SngORna+7chOskdqbZGVwum33ljzVSsVZx/JCWajpD4Cy9W9JnlPbjoNwo+nitwrmzlb6Mgj/GLGBctvl0wJ9YYFoNcwBSAfIn3HmEJOnbuG/9trSsuxvSovrI4LUMjARu5pS4vXyrBcl5DzxJ8Wh4wJkWYw26hr4DCBCQlqY8dsN77ClxaaV9OvmDJV9s0gnchYpQZhr6LnTDPqayJ51rr35eQtzP0dZ5jnprjaEl+iwSFPw5NAl0PvppKOy32oYs6608t7IjwjTkdlqqMScJCP9pJN5w4DoUUySSw6H08rAMwnYmyCaYX0c3UL37eOJ/zxB1jdcbaOzOHG6wYeS7qjPXV+GofJYO84Nq+ShjQeAExKjXoywFHMDdHhPqDfZtWF3b9a655D08JcQwba/lprkNf7Avr294XjY0iQAvv08K4NvjGj8ZLWpMc6R1nTv5TpKrSdJU1uM44TDlgtJ25VUYnlDZJQ0z/u4Ba+9eCEC5ydq7U0rwT6etfmPVeEczWb21i1A6pq5kzwjQ1yNU+kzfhBphg3gFPGxFe+v9aoplq5RAE0tuGgSyYG9FDmNmgMFzY+y0RJ5TGEbou30p554D7JyKrQwtDGDpUeRMrEFGdS+YOAUNQoUtJqXmaF0q60++NHM9yIMhUQyc2IbMsp8qb4uyepg8y6INZSfQNYigR+wyxRHNe0n0FkjX/Qt5f+yi+hjG09BLW8J/0xbQ0sqC1sRCkP9bk5O5GefIBRRm7lgJxjUxEn0ERAsmJ5cSQQhdjr5qjgMIyF1ZxNRNfIs1Yhs/qLzS+fgUBYUsNg3cd/UTvy3f/zhnlnYUaSvLaTw7v4guZxsVtlwnQ8wvAoVdt2YZQ2JRtNL4oz9H2wRbA5ke/yQfZRW3nqDi+d5+Gz/WHgUb/k,iv:PyuRD730RQLcX2NJYJzBes+DU6PdwBk/pTS82PoY7FU=,tag:fPBR2jgCv5rprGJEYjncqg==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUG9XZ0xiRWlTdHVidE9L
            N0dRMUR3N3hmVkpuSWxPM09BSWZXSHl2TWk4Cm9wVkZ2dE1LWFl6dUgwdTc4RjRk
            ckQvSC9CNXVheEVjcTZqVjgwcXlEY28KLS0tIFpMUTJuWGRGM2JvZERiMG9ObWk5
            ZDNCckhkVnNCWnhtbTE4OENmOGxLT2MKz6OTMBxLCMcVaaiynC5eFNg2mAa0JdnK
            YATfqe94jCQoY7kh516C3aEUaVnNqC5rtT3RclX5Fhaztt6U3ZJ2rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T06:12:40Z"
    mac: ENC[AES256_GCM,data:/R8Oabqs7X5GllJGUSF52EPCDRBjYZdc2RQlxU4ZH6+NMkdg6xb3jvn0pKttddDxKREhTfGqqOOXeJVfvg0OIucWuCs0wK7EHzB/w+cZZL+IUVglO11/TCoH6JwQD6/LQLunsXOuKqFb/+xj1bYaTJt6wZoFsHR+6enFFY/gdBE=,iv:tgCprn88Uz4JiIbpM9gjmAhn+cYUJZaUZ8W+gY0VlgE=,tag:6tqmvt8ILw1z5OIZdqpNLw==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
