apiVersion: v1
kind: Secret
metadata:
    name: n8n-git-ssh-webapps
    namespace: automation
type: Opaque
stringData:
    id_ed25519: ENC[AES256_GCM,data:Zh9gnRlMipH0DbxD5baZ20qF4E0x9ZJaC7pDksszbxr7eKFv4v8KB0osXz5XCEQSnrpmHshxGiK+iIxRu6FqWZFYFc5bVhAzGou50MpanlReVxRh3Mfg+FKRQsgbTrP3/6ZoUe9jOo263KTMF//T0lAET+D7MJVuc0141PBpTMFopfP6G4dB+EoSDmM5dH0G8GFdC3gV0wGhGOB783nV/tUL0YWfw90cQDIG8ztwcPahFH9dfSzduMaF/eWhNTin5mCJcAjTU1i43HXm84+dlViYPmHwD3wERYL41aQV/m0UfilkBxKQ8AKneX3xSn5LYTd5R9LjFQqvYXLnin34JMfWAWpBcpfTeeXeT8Jb1XKVsGs34XVC/AUyBaUkMWpVtZAoFtUsRbhgoXm5M+Ry/cxXGDfIwvajscbwq27HUz05w9EM9H2frEMZ3e4TZLf3cjh+dggmBqc/OuO7hcknK53qlSBl0HCd8o4h010fYsQGsgSkuBMdsWUqh+2QrH9uSLTkdoBambdsmGX24y5wXMNq2tlgEVgy1XMo,iv:pCavL3AcBBuj3LYRZEihCLmBHZZGVXTgs9q/M/Z/4VQ=,tag:QjEXFjbA032BsKznRQrIyg==,type:str]
    known_hosts: ENC[AES256_GCM,data:Kokhygy1NdI1AZ2+b8mKSjLsR+98PgVBNCUtEd74jgcKnGOmOy7+PlLh/Ug4g+1AjiQVEhl3RiKJwvR1DSoFNsri+PZhYfi6cyuuxBGZK/4mHkEnCRFX89dSSVua0hm9XJ/OLvBDYE7T85cirTZ68v2H+92VweZdUHMqZOIqCrez7KV7VBxQqgPD+MX9iy/pCFWAsIWaziJH4J+AHPBvWY9puOEwXXrji6vYouwgR5pJ2kEea43WyGpUzIsxPfp9yzAqBN9X19TlYe0s4sWidHXNsyuXR140oUGdT5LKoKadnwtUMtVK9zdzhP8+suw4/HUoKllS14ZZbWLksnkjnyrs5bOalJVCv6v76UDtnvuHDMjouI77NOpohpiJ6pn7txOT33hKsH/rp8J17C+Sl0nXUuZYMlqvpKgJbgih5n4ycE3FuH7nsUQ2CKre1/29EcZfyMIcsGgX2BfK81qYry9A9J3u81xs/Dbplv3R+gxIaMXSTX+V2kdg67bMPFkN6lFwuld4L1wHtnWKQ6XdooUppUqI2XYkbd+mTdfAXZMslhlS7msGowdY3JjJBMJm+6V6TMg2WFLhzbm+QQ8gC5cipkhBZ9Fhtl0LCSfAjZqmXNpmvlwIMV2IGcd9MHiGE2qO5ypEJL1dSUKaTLzML++tlsVyZcAtY8Q3T2qwy+yjQti74U7oV6kZCVRNCDXvatIO+RZBlP9rb/V18iODHO+n8g/nUu6OCH1k6JqFulubhRHM9XjTsFrKfVf9hbX5jffP7Dg6G2dzgp+P15PcrIAVLOvu1Nt3OZTISocoOx0QtWDtbx3MjMbEVbZmrCbe+Fc9Sj5C+nD0Xy3PrI295NmqfpookAVcS07RNxX5rQQQXlha6iadKKlWKlTuuH1zO7I53rRbdVgq6BPetla64GoI/dcqH6O9cQsC3O8AhJ9v70AoSocg/PvEtH2YiQS/Wkj/gG3SOtV54pe9kmQ9DKbY5jSne6leafeVIZo33vDXkoEz0KQmhfzfAhtLu5hqurq4Fgkv0f1fYEIQNriyiXQXlVeBIqnxxbV4pVVeE/B9PtnyOwabWcDFqtuD725/Dsl8uNU08FfWvGec,iv:He8wW/O0QP7mQNAS2jGIfPV4Dq7DKdVG98u1jZNFlGI=,tag:EiTuPi6sICOM1OElpnPcQA==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMHd0Z3JZS3RRZFgreDJM
            d0doMElQeUMzamcxQTVQcE50TjY1UUdxRlFzCnhCSFJLekFERXlWMUhhYTBLQU5N
            NFVhVS9EV2lhSlhMZkNUYWI4MURQZXcKLS0tIDhOWWJLeXE1Y01GUnJ6US9TTlZx
            K2MzaTBOSjA1R0FJVko2QWpweWg2czQKU/2PhAO9KxojE0ah+rpjthwb32pb8X0M
            bNmf152b7SvQ7OHZZ2eWlVS3KyjuVy6RY4BOsB1Pd1fM538EkfDxRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T08:55:58Z"
    mac: ENC[AES256_GCM,data:rn0jVtCau916MekckiliX5uW6nW0+7+tfSzT0de6ZgoLb9VXsXnAS0iwL7PeP3IzHCbekIhgALHbDE/+5Hmou5Hb9C7sdC5/m/6oOvr4lcV4dFv35OiaGVW+9Z3aNEHgmfVrcvtCJ1PjSIZjOR7eSP8Eq3gdM1gEwKM9EcLuqRE=,iv:YZrJ3gYWiif8czw/BKe1jGwmYCamEhmtGcG+FTUhEsM=,tag:X+ZMMFZTN4xy2ExKIDoC1Q==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
