apiVersion: v1
kind: Secret
metadata:
    name: n8n-config
    namespace: automation
type: Opaque
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:B8jUizdCIJKS1opD52t7DxkhA8h0KfXoXfLndEAtI1w=,iv:MX12jfTSP/pKaQkUNVMWgpJLewS3WnlSHW+UfRrd/t0=,tag:+uAK0tSjj1wqCeoNVoRZqw==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZVRmOTZoNDRDbk5qQTBw
            b1p3ME9yVkVQZnNMaWd6VTNtenV0V2h3TzBFClUzMjdsMVdvdllhQW4xOU9YZVhl
            SUI4S1pFcTJvMVZETHUyS1c5SHY3SEkKLS0tIEhXQTYyRXI1WTVCL2ZjQzN2QjI2
            NVB3U2dCREhaTDRsRVk3TlFOeUpVWHcKTsC1PW3VCj9YG5h64jdPX0weu8JHPuC1
            ZdW/OSMjvnZT4Upl0wOM0KbIedorL9HOBQXzH1DxLvxuh+vV1TZKlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T18:21:36Z"
    mac: ENC[AES256_GCM,data:12zN5AYTWsq4dUPUu3Y181h4VOGvu5y8LOdUMQX7nRKuE4tugKu6TBNyeb5akg+xMxtcPkJeY6PsO9DCSlX20MtbL2jE1zL5n54t1Ipw/03iKujcdhVk2I2FwX4SATw7EYLRo3yti4+heKna1FFh0Bhjnno5emoWjLvyOVGFNi8=,iv:qE/sGwc+khv0Y8UgTPV7shzHFLWBluvOZZmK+YS4nAA=,tag:8iJvNwBiyNB6W3+JjoKTPw==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
