apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: network
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:/EumawEVR21Dytr/4LBCMphJh+0eY7dt4pTgbEYVOUD9KIpUiMzs8g==,iv:6jEkp41Wb4HaOMmylj5odf0YmzeDSZ1dEUyyazkWQLI=,tag:jv/JbXfs/8zw7FAIfZRRXA==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WFFkdjM2TGJza3p2YTYz
            alNzTGdkSWpmTWlwK2hXcVlzZW1LYm5nTEcwCnl5bE5vUU5YUFlaSmNDVWQyRTMv
            dEZUcE8rbXVZWE91bTVCMy9nQ2Z0MVEKLS0tIHFrY2ZtVmJySjRXY3QrTXdaNmdK
            Y3lvWmwrL0lMbld6eG5QbUJVQ0xtQXMKJI2aO84Kb+moBtPYL4Mbc3S4V6RgZ+jm
            d2LH20HcnimvEA/Umu0Jhyn6ctUmSeyg0J1ESp6lTC7O3iUK2Qhf/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T06:12:27Z"
    mac: ENC[AES256_GCM,data:Zbz0NypbL63vFgoQhSaCh9iypXuZB4IuNrdfJ6x22O8DKX1Y98tjeXN4A+JlRhz9Vvmn7dwhwZxtz5zExlUksMkI6lR+swvDEWQa/ZIwNuJ7l66JvADcO1sf1U0y9Y12y1bjGBXLWJTRerJTpKSnqDB5JeatGgzjT/bDRy9X46I=,iv:yXuXboDUQXc0tNbSWXUE19jBKhxAN5ubsZB2PR1z8pw=,tag:ZdghOdKH8lgcQQush4/V/Q==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
