apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:dFry6zv9qXWUeANrFUDBalrXNd43UezyPukFptrMnJNMZ9hyPefZQ9MCiMM4+MNT,iv:l+P+lCn0UfyxvQlj5Vt/OQKvazlvv4KW2r9xTVMXnrY=,tag:+cM2A/FXBjt4P/jeTl//PA==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dkdyUklscmtHSk8rMnAr
            dnFzTnJjaWE3MWtBb3pkcnJhbWFJbHlkQVQwCjFwSzdHeDRJb1N4b3p1R0RhT2Fo
            WTlaTHpiQytiWG1vQi9hWmFwUXpTdzgKLS0tIE5QenZ2bXI2ZE1YK0orWU1WN0Zh
            MnZGTnZCQVBjdGM2bDlQNzBoSTdXUW8K3/gA1Cy6hFP7gAqa04ZnoiaSDFH5OHx5
            rAw6ujopbr+qbJMl/VAiLet46leXfVU9Me9QsWIOl1/f7/xNyPuClQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T11:46:06Z"
    mac: ENC[AES256_GCM,data:lAHVexA4sshAfewxXuTp9yVD3qOeDmH3Xp7l0Ild/O690b47pPnPTR9SCFiREpirRBsx+wtcL/hyBcZn5wn9AgmCTwzFGG+6r2Mj09m26FgDGtwbNoIL0eXsG/IOFk6U5pVoc8u0zG40xajcWzPLJvM7Ti6u8Dd+O0ZP44Jb7Tw=,iv:rbZ7Lmxo0/YIZqqWElFV3CkbME4rgzu1gNdXQv29sFc=,tag:rr3qACNAJNoK25V/ZlE0JQ==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
