apiVersion: v1
kind: Secret
metadata:
    name: registry-credentials
    namespace: registry
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: dynamic-apps
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: dynamic-apps
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:ii85OWfWLyAqjYlZh2z606oN5B3ez39RrweSwvPQRXUpptYfeniQ+S3lZtPA6hD+ZGSJYRm1TJZrM6l2VfNgPD53E4wZln3aQTsZU4fXU4SpTUIWZ/tnEPDBB3sVJKCG3orh/CG+W/gCtL8X7VnnCKCao//5gizJjLHOduhDpBFPSXdDD9cgiPQpZZUeKWdJEMxhb/xq6Tf7OmFgH1fByLyRW9iBQRD4a2qCatEooeogbfApbHtDhyYaXRXfapdI2Z/kOUgtIDx82c+8wzg5ZA7n0hJeb3LpZLF5y1nrO82uTkWV4fjlmkX+1xDz/EgWrKmcYHmMFeRY2RhigBM8z7XnXnsVYd+pwPfYD7Lz3Kmbi51Ld5xJ3BdyDGUkkMq8WmUP3v+L3Zo7dnPJ0lUp8MpSUe4/JJKWvDOpL5qwa0PoGRkmAxlAf6ekSHaQVuqj9ammz/R8EZoFUtmdgfuU9dmdte5bPLpI8sq3UdL6SsJQh5bqxAtft5Nb7G1OjZmyQJfOBlOi8YiUGDzslulrsviLMG0zN4Stdg==,iv:MMbHfSg6uoFjYFfRS4btcix1097SbX7rk/lb07ytXiE=,tag:R49uA9R7hQLLZYKrGRxwOw==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNVlpVklBVnpzd1RGd0hF
            NWZtdGUrcUdDYUJzdnBmUGU4NGxyOHJScW5zCjFJMkZkdm5NRS9BK0tvbkYxR204
            ZEl5SjBJRFFpejFVMFBWRnRqWXY0MlEKLS0tIDRsSFloM01XT3NlYjJEdWVjRUZq
            Vjl6ekxLWmVnNnppZmtYTkkyVmpIajAK+4WCKXSsHhwuoVBuPEF7AmlcLLMxb1lc
            Byoqed8cDUTMDD6UJ6a7InVyH4KiKzZg4ATi1ro5ujphP44d3K5P1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T14:18:16Z"
    mac: ENC[AES256_GCM,data:/LEk56/Sixs2V7aPHzXDGy5gAAN6MfAiqUonYnjz++DuU9qCSsN16JBAX26XEo9jcCub7vclgQ1lg1veFO1UjINogQTi/rzsEH6g6BYaapSo54vS/WcunuTZHG7w7wPR5IiZQIN5Jku+bhgW3h1lB4cpq1fI7G+aIoR1FHqmtL0=,iv:LKa3tesblO048GMPrtvCDJTeB4+laWt8Cp8+IfOx9gA=,tag:brg1MmOTSKWiR2QkXpTa5A==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
