apiVersion: v1
kind: Secret
metadata:
    name: registry-credentials
    namespace: registry
type: kubernetes.io/dockerconfigjson
stringData:
    #ENC[AES256_GCM,data:5h9hskYtR5Vj16NXjrvrkwXSOR6IpJsoLP5z0txwwFuinZJK2iALNF71OHJkC5g=,iv:DBjMgrOrualq2YeXc2B1qHuWIqF3CM3IXNLnJOJ0kzQ=,tag:2bv+o87w9jqMPFMBNfDmyg==,type:comment]
    #ENC[AES256_GCM,data:a/jCL50mOck6hPnpkxcmUtmoydcvCqNbpO0fVVy6tIU=,iv:7afhdsVGjem6kJLRRlolyD8kLBMksnFd3Zy86nY8VnE=,tag:n7lPbFmWHNqmp//nNznRPw==,type:comment]
    #
    #ENC[AES256_GCM,data:CbwOkDXQPnW+Z1S3g9ztpCnzMDijhHAY4aX8+czmCWNo7Bi8tp1z97ThaA==,iv:PYxlrXDpJ9Nmg9vZR6s3BKObvLyHNC7UmLRO+ibAhRk=,tag:5y2rFNAerVLR2+LUJ/VH4w==,type:comment]
    .dockerconfigjson: ENC[AES256_GCM,data:PM3KnbVGndtkqnM62q2KU7az8c7kTB/JaZoCMMjZWYSUJZWYnNvmJi7mzwl+2euyRbNVenCTp72s5K2/VcLf5ocm6cQavGcIZVnC9W4wXtHfRNoeY3LgxkDfKRrwJquCRyIsHwzj9HyCFA/7+DRV0Rb5v0sNp34DbcA5YzNVoFespqgbsbXVbsImjJ/OADOx97dosxuHyHG12mmT7Lsty1vS+LDIl0Fmx69swjGCIsvOl4J+SYq3hRNnM57N4HLEKmn8EUd3t9GdAq9sKrwYccX66SQScZpLoJIgv0cXYDqcUE6P,iv:gQ7XDcAoeinygzFx9uJ7lvIE/IMYaosp2rOsfsmV+8E=,tag:BjkZbRiX++7Nv9eOwGWS7Q==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS1hjNWNta09uVHdGN0Nr
            U3VaUkZZSklFK25VbUl1bXNtbXpmNkdsSWtrCnJyT2hmZlN2ekkxRUtTZVRqR0lM
            aDJoT3NVM21ZdmRoRUc4ME5FbW9lYmcKLS0tIG1lcHVKeXRLVTJDSGRsL3pKbU5B
            OUZFV0Z5MDJrVEJVTHdGcEpYZ2hMdUUKmao7VRXlLJPp+M8CvEvcEUV9iTfGKWDE
            PYab+5ZJ6eXG/3NmqCVFm64f32E72/lWfBQgHdUZFbqmQR+ui/krAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T08:48:07Z"
    mac: ENC[AES256_GCM,data:hq70PVgGAFrL9Ly0O+IZ/zb+LjwY9+Ifhzt4IftV+YN9DV+l+Kw4Wvvjt1ehFDVpkkF8P4OS8ITTs3DK29ixRd5Jp+jYCqzXmwmC8/dFzu8vGwQLjKR2pWEiQtFroh3GNKjY9Fw2z5aoivUhr5REfBHbuP+o/2phSXjbwkWClIc=,iv:bmnoZhdTuwg4zFzfdQ+1+RrWTu1WoftxAnQ8PVVa08s=,tag:yTXGdWwgQ1KYgzi+oLL4dw==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
