apiVersion: v1
kind: Secret
metadata:
    name: registry-credentials
    namespace: registry
type: kubernetes.io/dockerconfigjson
stringData:
    #ENC[AES256_GCM,data:uIFtBU4qj7+Iu9wAVOnzZH83vwVa9lxTtKqL0lK4IXqTavWVWkuTOkeAiSWxBx0=,iv:g7usiRIU1RVL75xzr2u58AuktFY8t365ak3v3PWa7Lc=,tag:tvlNUpt9ngORODNHjQ82IA==,type:comment]
    #ENC[AES256_GCM,data:LAu11a+rhT13Z26QLll1CXziWq06CMaHcUBhq5epoZA=,iv:EK/crJ2ixzxU7iDK/kcN6nMkSEtJUEfQooll/HXefJM=,tag:L/+Bh6cV4OTrocSa1DIJiw==,type:comment]
    #
    #ENC[AES256_GCM,data:3CsoZanZerYErMnUbZwinGw9lZIBDLEUoaVIHui/fwuiAMnMFx8gTGlN1w==,iv:F1sgDBdsS6OE/Hg5MUeNo8vV1jwhMfh5W+uQaWr8KXY=,tag:uR5Q+ydQbRLdnvaSfr+bUA==,type:comment]
    .dockerconfigjson: ENC[AES256_GCM,data:f+vo19xdLoBHS+NIMlesebSJUR+D18XH7D+bLqcbL98syPfD4HpnDbsaNi8w7DlzsOqG2OFu/9i2Gp+RFNBeomMC+q9xizkwwTNHz1KWaswtebfhBKmk3lRkXoTR5ojo+hknqHajmxMwAWLYFED0LSq2VarzWRckBXBeyBLL8YCXtxv5w2ifY9wVoJw++/wf2U5X7tHfvzuJCKmUAtesgr0R7qskvNlxeJfS5P3OQ8zw5ZJsegY9Wh/z3hppHU7Wnse5jqUIltVYf9g1Jz0r01ScPbtYf4q9hRSWWRH4JJZ8yP4u,iv:pS7OCmczyuV2ttJrgWa42CsSVUzkbp3cBY4intGV6VQ=,tag:t6hPSZUtfhGGUW3d8ONPIw==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudFU2MkNNZ2hEbFN3cHZr
            OTRUVDNuWU1ROUo1R3FxQ3NIdlIvcXV1Mml3CkZ5d3Nhbkg1ZUMzMm5BK1dKZTFK
            OUtGTExZZWRSb01RaldQR0pJSXZ6NUUKLS0tIFIyUXFSMTZTVnkwbDdLcFE1TlZv
            ditaVXBZcmU1UlpUTlJZblE3aDFLMmcK1Hzx+MU7fcH1qoFUer2qmUbc6rD/BbFK
            G4+PAjnMv+azNUnZ4rBhMtKjj0jeMP6sDNCkUXWbyeh37L+85AaDBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T05:46:34Z"
    mac: ENC[AES256_GCM,data:ywlu+f4upGVJaHk3Ix+hhV8L09CaPehcoH357XRWuyWpnBxii+i/Xnc0/0eaO0dXxNMIPud0ADv/OGyhSyBgIzE485tdS1WtNNmb59duYxI/TKJsWwQ6SnukdMNLG78/B494b7o2X48TfLATL6w6Vc5+XYMGW2e/yHuSpgC1edM=,iv:pIvsLmgfF+S/fygUQZDgBnxeUUiDsnjJtskDZ0c1la0=,tag:8txvf1Pvn1Rbs65UL3KI1A==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
