---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: registry
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.k8s-lab.dev": {
          "username": "n8n",
          "password": "n8n-registry-password-change-me",
          "auth": "bjhuOm44bi1yZWdpc3RyeS1wYXNzd29yZC1jaGFuZ2UtbWU="
        }
      }
    }
