apiVersion: v1
kind: Secret
metadata:
    name: registry-credentials
    namespace: registry
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: dynamic-apps,build-system
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: dynamic-apps,build-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:kyXOpFelVaIddXdNpijveo4hhJ2w4Czaxji/JYqm776q0AWOQYF34nosr+QBZcSisWA4vFk9yPZG12IIc3OVB9wX5PzL2vBqBkT/EIwJ1+dujX/IUJbS9tFKjDH3eqKW5Tn5tPxsKcdPyPT3t4N55rkM+aOSXLsdG3coJvs3/Zx3zX+2Z3KrdQRtZdJ48dB7kSdu3tDOMkN9H+neGy7kbnU2uAmHY7VdNCWooR/Rezt6p6wWjXh39wmlW/Ef6uxykwDeRm6QOTuxrMeI8KZXXwEgODdSbn9RZmBy7iSQVcuR52YfTI5kgAjgCTEHseSoyOyIssZOOKcgwxLcGPwcpBfWNQRhZraGA5WK+H3b4yzl8c9wrLupj4JLLmaSrMpuKBBKoUg14xNnng7qPpsHPTfcKV1N9JbLRZmCHF7LDIqibyp30Q6/cpopv64JcRmgLtGF6UUqa1lzH/cnZ68Co4+YsxDFzBQr1SwusbwLOAL6rFWagBcC91iGIpRTk9KruoH3yQzJUefrw85tMcCFG9WzTb8TNHyaXQ==,iv:5B+wZ6f4LwfiKqiDdiDm3OWrZI98sExbihF9IHiefJU=,tag:1WCG1pT8CvTxF/hj/oYS/g==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsc0pHTmx4bUt0eXI5UzEz
            cFRsY0ZEODY1bVRJUTByNks0QVdoVnFITDFNClM5L1lYcVA1b0N0M25sSTg2b1d4
            N3dXeG5VSkNoeENIbkI3MDNNZFl0VkkKLS0tIDlKZ0dpOFNpZlpxbnZqK1ZjeDdx
            UHdnNmQxRUpYWDdYTkVOZUNZNklZbzAKZhwyCda4gwvitQ8SY8AAIp1XIimxrY+c
            +JYiykByralFPs4yroBxor0pfdaXqtrLPgZn10ZWOJMuBA2nwqdXDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T13:34:36Z"
    mac: ENC[AES256_GCM,data:CddzG+ITURp+rpR0fLO84EKqs3fkYmSzIQAnqEXPuHohrtQOzrubYOPamHTahsxehkandvv4q5uPUGNJDTzznvE20enyYgnPIGip807R6nfZyjyK7IdJrsguaTxUPhCoCyRq0z03A2FzT5kF3qlOqbsif0iH3RYMp6z1IchRcmQ=,iv:ymbeFkaqCwUgZXsib3Z+sz33tpAEOEF0b4f6X8HpJPU=,tag:joQ4eW8XgwRVVOsXzDCyFQ==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
