apiVersion: v1
kind: Secret
metadata:
    name: registry-htpasswd
    namespace: registry
type: Opaque
stringData:
    #ENC[AES256_GCM,data:XIjdvPYcsL68pFhkHOJyAY+vmUqVbt3Uk/EMwlZ6RrK1HqlmOn72cNm8EanIGV3g,iv:8+cFull6ir484CSHOuhiZ9rbGbvAmYRB3AiqBQ380E4=,tag:889T2/RvarVo1LNSSa+PDg==,type:comment]
    #ENC[AES256_GCM,data:7LUBTqX/Byxo7vljKDmYUbLL9rR/rk2GVWh4yVYqurtVoL+m5B9UoA0Fjxf67+umHRUTerESjk/UNDuK9411jgPmYw==,iv:gCre34u1h7JfhqCGgfAQzMHswpJHYI1a/3ppo41Uzkw=,tag:I84MScgWVU34lml5rUrNTw==,type:comment]
    #ENC[AES256_GCM,data:lxNBA5pDolqYP3ueKtH8+kihhQdl6Pfn3PNLPRazgCcNjAWuQicIrmxDF3sPOxgy,iv:Y7c9ayy7pLriBxpL38+ANqYDM7r5da5AqvGnUBmIzvU=,tag:Sic2edD84RgBYcKGxNFSOg==,type:comment]
    #
    #ENC[AES256_GCM,data:an88r9RxoVf0bGGtGBOp8pXhNVkQhfqarMOy7q5+oBoO7kl5y415z2rskmhlkw==,iv:PQfYjghTVidvqRWJTyH+/zudKnkGL9VZD7mhugw5ftw=,tag:k4udzumBF18rINWt93x2/A==,type:comment]
    #ENC[AES256_GCM,data:lB5mKRjAIS5ZjelR0d9xZMf4eNZCioFEAWthlYVpPHIiZPeEAZdH5w==,iv:aLl+rwuTQko3aMlxf/42QBYSECTbKE4ESgKeeXiQOWg=,tag:QIcV/mvVWapxzCHoTmOfbA==,type:comment]
    #ENC[AES256_GCM,data:jSC0OTbdbhLg1gHHaQv8RUc7JGOCCXvF4Os394XScDKMo+HX1JfqdQ==,iv:y++qbq+N5fB1PiQXTiQOd96WA60yuCqv9a9xUJouCwk=,tag:gB8XLr6hvpDqOfQtYNZJNw==,type:comment]
    htpasswd: ENC[AES256_GCM,data:6hQmjXtIeGJ7jJAg45/MY14pOuhi4Kdg/SPRfsAKdLucVxfFc7fN2TAxKR29DDwmCxIkGMWpp0r4oCLQU1lLO4R7rfgK1BZXt85WfGMGpNkgUo3ILf5RLVd5vk2LaixJd7iYa9aNTVfFehew2s0rzs3L4aZSrjN4kbI5KgZEgzE8dphX,iv:f+8TthkSwr3DU4Sj44Dww35L2Aq+rZt+9ULmh27l1Bg=,tag:ntFcgf+wjHjDpEdDF6ZcrQ==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UlpmdllaQk9xMVNnYTZL
            YzJWVjRLYWxxYnd0SmpqYlIxc0dhM25jcmx3CjJhWk13anJHRFVFazJIVWhCRUVT
            WitMZFZkK01iMHBGYjFrdHZlUFphdzAKLS0tIFBqOFlrL3hhM0VtSHFVT1RvRWl1
            WTZGSFFhdXB3ZTBLSytTR2dhSFZtMjQKWHQqq6W3EwEJHcyi/yGJFk5VfhWcyKnL
            v99x8aghUU+feLk9EP/wEKW1ptvrKQG4qGRZONd9t8f1nt+k6LPZiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T08:47:53Z"
    mac: ENC[AES256_GCM,data:48sFdanE5I09XjSjNR2ig/lCA5JTLz957hCWjDxL3ds64mhpfxk8FLHUNbvwCfn+X7hvDJ+HkRRP0kV5R3+vCl0FhgNv52CiQH9ErfsU0M7mjxWtWzGAqL2HcVMlPEziv/FT8/gP8jyiA7Bns9DJyLjIxZ/pY5uWuhpRxgNdNY4=,iv:oYTIO1x0yL6RNH6MPm7hv177xSn5+t72HGXu+qeuou8=,tag:2JtDJV20dah9xL1xwKpNFg==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
