apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-credentials
    namespace: security
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: automation
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:RrnUXAH2j3bqkZhOHinUMW9eU4gzv60QExvEFpFhG1xlSb+ErEMeOxd6xCKEm3eJwjZpIIFu/QIPxPBZL6qC4Pl+b01oul8HMSJVUDHeFeQ2rBRQpXAL0a7R3KbckAZZk30Sa10eKug23InXWim9iQ/UyW3p4Me00C8eLgouRQDflLKHuT9LO0YXJQcT3x3wKsy9Q93m96hWTpX0Z6AspPlt53m9VU3BiQlunlCMPD5QoUrXcFiUSFnNZPRwasQymqdKy5lmirUnfbhp4RUwJcv/lWESfbnRGxDpJXTyCfLmiJ/a,iv:8G24Ger3/iS1LEf8kCgWpOEVLsWd0SWa8gEiEEg0niI=,tag:VBn5DjWD5rUF9FDniwTU2A==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVkVYa2wzVEZLZFQ4Yzl4
            MC9KZlFlcVZINTJaRnkzek5QekxNc3lMQ2lnCkFEdVVwaW1nejU5M3Bka05Xcy9s
            T0tCaDN1clpRQnFrWStIbHRVd0RIc3MKLS0tIDNoVkZMSlBPMHhZTitpOGZKOWI0
            MitYV09sTHB4UlU5TDZXbGNQTFExNjAKXP9JIhoF/G1qlZflX9MUFmyl8x9o5WGE
            RKVhnXSFOqn7qGDZCK0Vso2GU8y4YoZWKjaUnlz6ExnwaI23vWo+BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T19:35:21Z"
    mac: ENC[AES256_GCM,data:60xsZpV25comDdNlHdXT/nHwfuEHN54rW65z4QMRbxpQJ5nGXUvkL8gPm+Sxwg1Ayznx5Z06wsP79KnuccMDFQIycQJ9nCfwNpZNjGC2x7VuaON/tOJlsOJqCbw+tP8RdVSyVjNoj86NLnDnsGbIFUxJqIb78QgWVq9rHtq6cDQ=,iv:OJiqjm8luUHoT9IfCPyBH08JN1wB1Y2+xckp3xQh3ak=,tag:sbnVry7FYJ94YZ7XonTbYw==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
