apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-credentials
    namespace: security
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: automation,network,build-system
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: automation,network,build-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:7f8ck4Iu7qSFW97yoju/goMRdF6x7uC27pzpp0C+r6NSy0TXDyJkB24eyOyZRXLZio15ezIhXCu2GNIJ5rXXcCYW7oI77zawB4l4Ogf/foLjaYYwgjEOnBQN97LZOwBH+r66sXf8pdfP4TDvHSHMges9OzdHXvPvDo0ybZVwqzIJT+hysRBVB7k6LDh8zyW2YNduJaLnJGO+g7H5dfoeEXIW4dtdhrfGkuu6GruLDqIxqKkDkVmpyiiMjlKgDngFqWHaoM2T36XM85o+MKSr5vWHkEs9+9BtCTXvPLhkrZvASIak,iv:xSmg00/Em0uZzPeO9E0sVi+j50AbaVCqBIZBKDCgk+w=,tag:sIBtzeJagkgDDa1qbU3yfw==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbUdBVjdFVGptRG5EUjFO
            VXhQejdSbU1NVmQ0OVNjK24vZ1VEVGE4UG5JCnN4aHVlVkNKVFVqTjRDZWdpNTNw
            REdLeWltZkdSem9NUWlsb25OUGxvV28KLS0tIGpoZy9ndWdZUjBBcmhmMllvdUJi
            VHo0MkN6cWwwcGVOWklSZmV5bkRadmsKAuVe+qaLpN52wePcEmBsjGLmiKRr8j9A
            MUlzgSg+87qpz86bqXD6oUPzTs7+yBu5IYCiF24Oh8+mnzWzvdjnVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-18T13:33:26Z"
    mac: ENC[AES256_GCM,data:h7WJkahn2Q6/sWEzng+wEd8qXRngi+8cJIWyg1OvEmNRAT58M5ZkRvHPGSLr1UraIUmp5uTi/WYMjtIQBIJZMESsH2bIkhlGOSQC9HKJct/fourDjJfj+lXl+wR2Q3bup3ezwuh3UK0VKliJtVM+SI5o/MKzWZJ+4ypzWmyWSvs=,iv:o03d90n8SoZEt2PPusuPxNu/NDLcx7RZOexH1L4dvQc=,tag:bvGSjCTQzZcYItASbVQN2w==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
