apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-credentials
    namespace: security
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "automation"
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:auZdy1I49P7CIlA5Hn7B+PAdSGf4jwCmIhGqnhiSBQZm6qcHqNy8CHFw6hU7LiWIGPqFKnVpBN7f85XKR2EzAvxegzP//AnKZlJ9Tz0VzBoSTFLRado/VQW17H9prhN/vcouYJjeyupwRe6J6T2ReocZAVOcBcML+Hi+u77v/PzWqzTzuIm559knD7ykxttPEl5W1j0mduPVLBK3cm6Mz028JsB2jA49btFrdWnW553zyd8386z9v1fx0CH2gdseSNmhHyrgZRib6dkjCaygywHqMctNqyATbjpuQnn7cwTc7iHa,iv:O+PeOLbDz4cAdGFoMkhKYKl7DOmbSN1FNYP5wWO4aVI=,tag:lw7CPuOo/eNSPPmkZ/ZwbQ==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwa0JROFpNc3BQNVVtTVV0
            aXNOV0tqaG14MGRaNWFXL2YvN1lXL2xSc21FCnIyNXFaWGJGODF6Tm1nVE5mZ1hW
            UGVMTTBsd2IzSUhDZlFCZ3grQVU1T0EKLS0tIEJwa1lJQTlFb1IzeDhiVlByb0xn
            NWM3Z2dRYVRpN1lUdWVQcmRCRUlMdUUK99F6QalToyyz0R4lRpi7jO8RZ2OkEmgT
            kkpljl34UscNKJMO7A6evRWVS6ZUbxZHV9UaBkwlgrVnsOWqBGBLIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T19:21:45Z"
    mac: ENC[AES256_GCM,data:yNQenfp/UqwDrmbYIRaIlHIodfmQVft1gs/IoO+g+yPreTf/uHp1pOTqtKIm91ENCz4iI3uguMwaN8kknN1umpPGyODV1kMAS3KTK+9H3M+6K4rcUOgXVzPp3WhZwOU8hwtJ/rF+Il3BED37wIFzXA4RAN4rvSPg7DLi+fQmjCc=,iv:RNpWVleK+W8oHEkJ+yRGj9pXXVcPFG9lTpPPWX96JYU=,tag:Ypm/QX4Y8oG5woUNze126w==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
