apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-credentials
    namespace: security
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: automation,network
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: automation,network
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:J//KKswJRlTRY8mjKqSdcj8Sf+fb99fzYzLNS2DicNpW+I4tt+A9vMjYyDQNspf3/PcC6SR5rsutuNUb8/5+fpz/BqmRDI1S14WSuAQAmioGiewrZdy/X+0vW7HlYucgqOrOSgUMvmFQ8V9XNmpYdhWXT3P7AzdFY614m+HXrmBc/3qviJuD1LEZSZTNAb147hNov7mJtnmCeawsYH/k+ugQGdUDuMm7jGhy8dGUB/1BY9vWa6G5iO9djXqhBdMJxJwXLKk4paTg0ROfzmY14aiSfH+FqP2HGazBG6eKTBPr6ums,iv:KwzKEw6hao1ZSz3UZk9fVnxFwjGYlXks0mMZmINBhm4=,tag:KNFMcEgnnE9fpopJOICTWw==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCczdveEZpMENBaGZ5MkE2
            eVVrUDB1WG4wd0hxMmpHa1o4N3VabG1XaldVCkFaMWVlK1J6TmpFRU5JODZ6Uy95
            aTRBblc5bndMMzhJWVd5Z1Y4S1Q1cEUKLS0tIE5tSm56cy90dUlKcEtEZ09HNGF1
            SEtpNGdKTXpySFowSnJ2Z1R5emsrVHcKXPMbYLHwaxWwVIWvyMIP0REZDDt+YEBn
            PI7IWUDoXzyrSPJd/CNk6/AWh1Sjtdp3eGTTcjneLLWcOYNyaQopIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T06:48:54Z"
    mac: ENC[AES256_GCM,data:RiPtg5KdpYPJ+XD+ucv23GQCjcup7EvXx6mzjjyGGKWeoRWzucrfpaiC0ZIFTqU/aAtA0o2ZpU+0ashIxuZ7ZECDaJVev9xoJBy8buKX8iD6NlsVAM2GQy9lG8CXkHMkBialwgytBInimejTuk/7LBLlBDi+8VWCMqD7/52bMg8=,iv:9Mn6v9wDlvtUIwRpnwX/28KQ0C84EA5JRXhhbBDCG9k=,tag:ZTg5kcvCPVtK1+6QavB1vA==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
