apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-credentials
    namespace: security
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: automation
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: automation
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:OWleOzGsOw4CcN962wtgOdTkmYfgbWK/Sp9TjUzy/QRucreoAVX1vqt3e+R61qXOtI8uCWW0bxXx78+OTk6+QO0+cahsOtDbgf3N6J0gLZVYYJT0zQi0ZW4S4Blf+hfuo2QAvT356UN2v84xv349bA5sg9NgY6OPaKIhMqjFPq9Sge33V/p+P3H2oA1mZbHj4OxdDxL7Ko1kKnxu+Bql31kgxS4vWxha7edN4ijHT5V7RSLIFEAzIepz/EfDNRh52oH3kWuZRXAvfD5KrCghWWII/ozNMPKZvIKxDMLMwkQG0w6N,iv:jiyr89wB0sfiWIBe/e3bp9um0X8mO3WbPaO6ssPIOUg=,tag:6kewFDdA2ZnCctooeniMyw==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc3g2dXhva0Zaa2Y5RHps
            V2I2UGNObGlZeG1wTlZrR1pFT1pVd2Nxa2lVCktQT2hRRnN2Vml6Mm5qbWRFL2RD
            d3dTSG5lYjdyNWZJeE1INHRLODF0SzgKLS0tIFFYWEJvSU5NMC9md2orSnAzLzR3
            cnF6MUpvN0Zld3JwL1lObmRhZ2tOZlUKvEGpLI+dfgUfiIxcAPDk9ZRjvca/YHQN
            lIjIkCpE08r5ojYPXqLgZmlMLopz7F4RlTTn9ZsU2lOljgAmiv5lcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T19:48:00Z"
    mac: ENC[AES256_GCM,data:eIrwssKx25gQtKr+E/8BcOlIrPgR0mpcxFy8M8KNzGwku9xyda3wsL8d/5bOkZ0s7prTkOrHas0W9qvWJZJT3VrXW4/tYh2hyH/svmxGzG+RWVz0YGlHUWqkim616o2fKScMs9XKUV5dL0FgC2EEataC9aC2yRAD93eNwDEk11c=,iv:omeoeZvFMRltf6jB4RZWpm5twjCKxCstd16fjg4BbFs=,tag:YwJJ6Cauj4Ao13JRk5UBlA==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
