---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: n8n
  namespace: flux-system
spec:
  dependsOn:
    - name: rook-ceph-rbd
    - name: cloudnative-pg-clusters
  interval: 1h
  path: ./kubernetes/rpi-cluster/apps/automation/n8n/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: automation
  decryption:
    provider: sops
    secretRef:
      name: flux-sops
  wait: true
  timeout: 5m
  retryInterval: 2m
