apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: network
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:TBBxkLe52c9v84n4u+DQcXotDGt4N6XggWswvKH+TnrRhKQZpGqP0P3Bn5mKOYBIPXf+EY0QBTljSwuppS5aB+C31gMqWv1s490rwtrS6NERRVmidxOEYPBnDhPio6os/2W8su7dWlp90X/lU9keBX0bKC4LK7aihnuELtUOS+Zo6kNIwXYNH0wU/ggwHh8OdMaoXN9j6Itww0M/t4BRrWeVRUpoeTp8HpeVVQCRY8o=,iv:aHbQohWI9j5vNxb6+h/8O0xFP6J7KPlTEYN/QnKgTeo=,tag:He0zDmdvGTpw2TjeuJ7S9g==,type:str]
    cert.pem: ENC[AES256_GCM,data:h31xgEcnzz7CztCtpJn9yyFGZrVL1eJxroBVKpmP3uc6ULrGjE0exdSGCd1fNb/bxGp7DlEihkslMdB+JB7rTeFbMRH/rMKeEUcGpiGkg80G/LU05c7t1oytUEgGqefrIHLQZO44WX/57MqReDdWIEswJ8mP41ibHRC5Nv4i03rQv6M01kA0JLZGh/FYScPbVONj7EfESnJoia/xB0qLhi/7scPR/SKK9Ly4pd/NsI6REzR6tzR8g/EnwfC0gu4h0oZ8/ohvmA0zEDtyAREh5WXqT+FEpM/zxI6pPJDZNHG9y6zZVJjxvqaeNJFQJzE8DO3lEOYoqqUzGraymw99ZLqlSynwJhdDPQQ=,iv:7bb2YUdCVVX1s43rSYRt2V6u/D26pWwvwzvGSDoXmi4=,tag:w1rirab1vAfBg27xQolGqQ==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSTlJdU56dTBvbVl2VnV6
            aHQ1bmpiaHlZRVJzVXp4M29HQi90T0diZjA0CmxLL21MVzg1aUJ1aEZDYUQydzRp
            RTJZODJpRVBHdlJzQ0xod1EzZzhZZFEKLS0tIFlUZm92a2J2OXVGSVFQZDcyMXJN
            WHVTdCtsU1FtTEhUZ01DK3BxSlpOUHMKhmZ+/HrPZBys22eSxpp4uiG5PdGX8bGW
            qGXzJThTirRoTmFIOYrEUfab4OChJlzYkP4Z3HV1lhL+p45YrgOszg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T05:35:19Z"
    mac: ENC[AES256_GCM,data:AY3hwRFDXjOCYQm2cRf+Os2mOli5bniXdFlLDqWiF8t32WK7mnpRuQU+gsDZS03jkP4UNLGOOp8ZMFKL56eN2XK7XVOimEiIui/ZkDQi1AZZrg8V/uC1z3l3YD5XlQiIruysuF0yLjZBqI25OZKIwAmBOxOZbP63LW2oWVVDHcs=,iv:uRh1hsKzCBMmInV3ZrmgmGriApdgdei2SuxsAPOmBKI=,tag:cV5VkyECxwQkz654hyduaA==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
