apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: network
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:TBBxkLe52c9v84n4u+DQcXotDGt4N6XggWswvKH+TnrRhKQZpGqP0P3Bn5mKOYBIPXf+EY0QBTljSwuppS5aB+C31gMqWv1s490rwtrS6NERRVmidxOEYPBnDhPio6os/2W8su7dWlp90X/lU9keBX0bKC4LK7aihnuELtUOS+Zo6kNIwXYNH0wU/ggwHh8OdMaoXN9j6Itww0M/t4BRrWeVRUpoeTp8HpeVVQCRY8o=,iv:aHbQohWI9j5vNxb6+h/8O0xFP6J7KPlTEYN/QnKgTeo=,tag:He0zDmdvGTpw2TjeuJ7S9g==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSTlJdU56dTBvbVl2VnV6
            aHQ1bmpiaHlZRVJzVXp4M29HQi90T0diZjA0CmxLL21MVzg1aUJ1aEZDYUQydzRp
            RTJZODJpRVBHdlJzQ0xod1EzZzhZZFEKLS0tIFlUZm92a2J2OXVGSVFQZDcyMXJN
            WHVTdCtsU1FtTEhUZ01DK3BxSlpOUHMKhmZ+/HrPZBys22eSxpp4uiG5PdGX8bGW
            qGXzJThTirRoTmFIOYrEUfab4OChJlzYkP4Z3HV1lhL+p45YrgOszg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T22:14:22Z"
    mac: ENC[AES256_GCM,data:mqnVQSs217B+vcmGv90ZjZipTWMUnf8AhTCckETWAewDjatm4V7whaEtmASSRQ1zKe+4mATsDNGVdSvsNc99ww+p7WFz5zr3+wQxNkix16ZnQPRExLJuMtOJsJg/ld114ZbIGI9+nrd52pzDZxZu5FpbGBS2/80pa45IH+QKcRc=,iv:m3g0EvDE5dIlZTzX7ZgLDzlUY72cMiT62sjYvhn2YDQ=,tag:e2JPtADSWxhRhChUDVeUeg==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
