---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: network
type: Opaque
stringData:
  # Cloudflare Tunnel token (injected via Flux postBuild substitution)
  TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
