apiVersion: v1
data:
    database: ENC[AES256_GCM,data:RmaTPw==,iv:vrt2FzqVD8i2NrQ1dTQjy8Mj2IFhAIgUk6iZbfSoq+I=,tag:cdQwlmrN6Ec1K6wptyRYkQ==,type:str]
    host: ENC[AES256_GCM,data:TpFiyNPe1zryrhA70m1GGW8T/j2P4CMOTeJ+NYdDP8KmTG8tHJwRg7MoPUSxW54HeT7ehhv5ww5S3gxMnfl5CQ==,iv:gEiUGRRx3soj6CLoYVvyrIDhSXAiu4CKID+L35Zihgc=,tag:H/xKpCArpADW1LeXsLqOog==,type:str]
    password: ENC[AES256_GCM,data:dwR1AXBxhC5kklwz/WAuBLUBOFwVKJxviBP5W68O3+SSbIsa4RTMcxlWk/s=,iv:PLusL4HaFNrt8lriXR4/a2K+V9HObKWunBw+TtQ3BSM=,tag:+wKRU8jM3S85bZaYv0ic0Q==,type:str]
    port: ENC[AES256_GCM,data:EIhVSfCh1tw=,iv:hJyOByteN27T0zbxLfxzIXfO7A75hY+cYkjbDpvTLMg=,tag:72sna+Tr4l00vtzXtOlNxg==,type:str]
    username: ENC[AES256_GCM,data:wJ2CNA==,iv:dkqclXQdSmEfzDAPEYuO04fANVXIBUMvCYuxP3OqtxI=,tag:kMrOgFNdCOUbjbgyCWDefw==,type:str]
kind: Secret
metadata:
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: automation
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: automation
    labels: null
    name: n8n-db-credentials
    namespace: datastore
type: Opaque
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbkt2OE4wU1ZUT3ZDa2Ns
            bFhWL3VtdHpTeDZhUlB0eWIvSFhXUm01Rmk0Ckw1MWhGbWZZL042a1FpdDF2SU8y
            YnEwY0cvQjcwOWtBTVdyeURSRDRlZXMKLS0tIG5vK3YvTWhoeVdtQkhzUEttWXIy
            Vi8rN0d3cnpVTVM1VWVWYVlzUFY4aE0KBqQA0vOAKbT2uwEdtV9FgMJdj8V6SV2v
            Ab2OwbjUnvh5RIdUvvOKg/0/1t0mINNF8oMqdfHp5YkwNcUsA5So1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T19:49:25Z"
    mac: ENC[AES256_GCM,data:CJRbsYyF8n+Oc/3VBZ0Qlfi7jEiKUPeYAkA8vwZbJD6kGTj3rIRH3ayb+XaE+su0Dec2W//I3tGcbKkK+bC52fdvjgf2ByD9NpRcHXt+msD/1LIKVyuIlaCML4BkMMeMthd4oNVj8u762cF/SRPUICqP0hYtJmKZSopgRYWGWu8=,iv:WGAXcdZwjuTYvvl72HDojQjqOodI6Du4xWzEzzaLeI0=,tag:egI60FMSe32cRU0ecxKLzA==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
