apiVersion: v1
kind: Secret
metadata:
    name: postgres-app-credentials
    namespace: datastore
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:H2gh,iv:2xNMckjOZQhQ7RQSRHk0mupktEhdWthuqRDqpHhpN2A=,tag:XERFHlreMZhCB861t73UkA==,type:str]
    password: ENC[AES256_GCM,data:5dhll65V4xU2ZQ==,iv:0Gde6883RQgCOwtiqwCHkpXifes/g9xsRMrxrfKMAXo=,tag:6siiABCGTp9jvWj54nygrA==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdHlDUUdqbGhNVzNsU1NM
            OUQ3QUJseEhQTUN3bGpRYzdQc3I5aTBmcGdNClJnVEhUN3N3cDNoTWdaeGpNRDNW
            VjJzWVBIRi9FZVc1a0JpSE1DRVo1MHMKLS0tIFVmK29FYVhLeWZnT3ZhWk5PeUVW
            SFRQMStCdnVjUUlxQWxmNG1OZjVvY0UKwp2xqcX6ADbsyQKOmN+oRnanulaTJuru
            jUXv1m70aC631KfHJSXgMt94504x6L0bVaePYPKQ/TWtHYWDJ9R1/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T06:59:06Z"
    mac: ENC[AES256_GCM,data:sd2nMHGOJhHuY0+B4NCXJc4e8215L05SzenfyXcck5nS7HKxUXSsDQsO7Y44Iq51Gs7PzRg8IK5KnTA07ATqoOfxbJ0bHK5u8jsfBWQ+G71fkoKnzrR7tcUv2L4yzCWu5XSL6iV44EJdbrbRvfnvaPmbTJnRY9LdidhrPayYuIU=,iv:5IJqKGoeB7M/k/wiU7Wnt6izEDRhYkYv0Y/7SclUiW4=,tag:0ISP4LZzLr+zPTtyaa9X5Q==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
