apiVersion: v1
kind: Secret
metadata:
    name: linkding-postgres-credentials
    namespace: datastore
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:CAZjEuiLkOE=,iv:Hw13KSVZnxUC2ZxRYBv3IPmO6QUPx5s0YQX5AFuMvDQ=,tag:vdPb97Vr1duQQBG2sjB+YA==,type:str]
    password: ENC[AES256_GCM,data:c3l1r67IT1PfrTK9MlV6LUpXEBbh9He2,iv:cHy+s+9r5YAOCxijDN/NTEoHe3KPYVj3b3dBSXgZipk=,tag:A4z1Fe0KvoHuBfd0b+9T0g==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SW5JekdleUZqdWpYY0VW
            ZW5qTmY1ZjFUWlVpMUZyLytsNU9FM1YxR3hFCno4b05FdWd1NUJNYmM2ZE9XeUU5
            ekNWNTdVbDFialMwK0kyeXR2U1E0WmcKLS0tIEx1TERXVVRYcDBxaUlVd21aUVRp
            eUlTZmF1OGJFUWZFMUxLYXcwV1oyMlEKl3/Emtmle+j8ogmUpm9YmIAtkPftbtVz
            erfKYS7OR9+yvgVDte/BbBaaJLfNV31csC+t5ynAe8hIBBPX313iWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T08:15:30Z"
    mac: ENC[AES256_GCM,data:28yHvTPOuAjV0sQ1VcSXjkIuJL833FavZ7Y2UOIAzKyXQw9E3LH4Xhcx/FDZVguydUqVclkxebFOaZHvd+BbuVRGry6A9/UwsyzLP9I+GKexre1HV9wDHJa/N/dxJeV+SNXqazAtAwMUcZtrX54exGjEwle5F4qgRaGjsSUFZkE=,iv:w3qUqJlyLWZAF9Ns/CPWuWMkKts9OPfThQvHoaxT18k=,tag:imoc7epErijHU0BCXOArtQ==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
