apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-credentials
    namespace: datastore
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "automation"
type: Opaque
stringData:
    #ENC[AES256_GCM,data:pga4TYBz4LPXZySFHOKSE8wwmFde3LEoZo0eY5ysqQ==,iv:/zaSybbyihHEnKZd36oZU3aFPW+ofOEjEvnTrdaSKic=,tag:i5HOCnCBMsCQgNu+UD59MA==,type:comment]
    username: ENC[AES256_GCM,data:KLta,iv:T6GdKdRb0TDRVf6eXEt5D29VuOpwrWBNIiLonMQkHT0=,tag:UbIkOSAm6i428MXuloUpZA==,type:str]
    password: ENC[AES256_GCM,data:/a7EkA9Fro81Nmj8GHaQXfRhkdmhpMRsa2eJXRx13vs=,iv:JTkBOrRMOcNP2VbH3+pLGIcvBWMTwBdXEGV039t5Oz4=,tag:eyYnAScGIzhjwj+gfthlgw==,type:str]
    database: ENC[AES256_GCM,data:Hu4I,iv:sR5zV0P1uzWq4ictg0urdtMA+YlSvW8BO+Kbxp+AqIU=,tag:ved3b4q2Blfkv+P4xPKiqw==,type:str]
    host: ENC[AES256_GCM,data:/laM3vxASA8NmcgJ26q3hvkJ/1Y7EZkV4Bz86kBRGexFj+bAyVgjNUQ1142G3Y4=,iv:fXJrZ4aPSYEWYtVQxO3QTbch7MJyIaLOu5zuLTgj29Y=,tag:FyYXni6AjhQmw6aJDZG7iA==,type:str]
    port: ENC[AES256_GCM,data:sdal/A==,iv:2mJnophAZiDZI6mxUxeW7eQmh6scB9CDRtfssGBQxZY=,tag:F9ylo2ZfI90COLR/OLEPcg==,type:str]
sops:
    age:
        - recipient: age12f3ry4kndhhzag52alez69qsfwm7ujd3qp3c9y570c5yhazcwqds4qhe3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR0hQUkZNRmp5RWhMOERM
            ZUdiWGRXbmxZUEc0bUV6T2lEMGZKRHoybldFCjdGeWt6S25LOEVqOXVSd0cwb2lv
            Z3l4ait5cVFKYVVKc2MzZ0dIT1BVSXcKLS0tIGh2RlFFSGdGSGVibm9rOGtUM3I5
            S3FXeDV2TEwybmRkZWlOZWdlUXBQNjAKDgjstmaSXdy/iZ4F39i/4npZ/WySbH5V
            aP8eOkVH0Q92d6KrpwDxB33lUBfdIgUYZvRZKId5uRat/3MMW0rcbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T18:00:36Z"
    mac: ENC[AES256_GCM,data:kssaf45mf5r98lDdfyKwyvcBgCOTjDP46Oj4lKyqcd+sSBl7qQKCjrV01sNPJ9wsiV1p327k1dPgHayozbzlnph/BHoaPiZMOYnxzsm6YfFMC2H2CY3d168/trmYVDgBUk6dNyUtUpmsgyxDq8ISQcycLe9vjzAfXEDfuPn/U+Q=,iv:/poMLZc+EdSbjBwlzvlLwE3qaizI6dVZkkwnc+1lVo4=,tag:955dmIqKHW1vMzT+pK3OOg==,type:str]
    encrypted_regex: (^data|stringData)$
    version: 3.10.2
