---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: linkding-db
  namespace: datastore
spec:
  name: linkding
  owner: linkding
  cluster:
    name: postgres-cluster
  ensure: present
