---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - credentials.sops.yaml
  - credentials-linkding.sops.yaml
  - credentials-n8n.sops.yaml
  - postgres-example.yaml
  - database-linkding.yaml
  - database-n8n.yaml
