---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: docker-registry
  namespace: flux-system
spec:
  dependsOn:
    - name: rook-ceph-rbd
  interval: 1h
  path: ./kubernetes/rpi-cluster/apps/registry/docker-registry/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: registry
  decryption:
    provider: sops
    secretRef:
      name: flux-sops
  wait: true
  timeout: 5m
  retryInterval: 2m
