---
apiVersion: v1
kind: Namespace
metadata:
  name: dynamic-apps
  labels:
    app.kubernetes.io/managed-by: flux
    toolkit.fluxcd.io/tenant: dynamic-apps
    networking.kubernetes.io/shared-gateway-access: "true"
