---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gateway/kustomization.yaml
  - ./storage/kustomization.yaml
  - ./network/kustomization.yaml
  - ./security/kustomization.yaml
  - ./database/kustomization.yaml
  - ./flux-webhook/ks.yaml
